# Generated by Django 4.2.7 on 2025-10-14 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of the 3D asset", max_length=255
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="Original URL from Sketchfab or other source"
                    ),
                ),
                (
                    "s3_url",
                    models.URLField(
                        blank=True,
                        help_text="CDN URL for the cached asset in S3",
                        null=True,
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        help_text="Original creator/author of the asset", max_length=255
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        help_text="License type (e.g., CC BY, CC BY-SA, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        default="glb",
                        help_text="File format (glb, gltf, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags/keywords for asset categorization",
                    ),
                ),
                (
                    "cached_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when asset was cached in S3",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "db_table": "projects_asset",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the project, auto-generated from first message",
                        max_length=255,
                    ),
                ),
                (
                    "scene_json",
                    models.JSONField(
                        blank=True,
                        help_text="Current 3D scene data in SceneJSON format",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owner of the project (null for anonymous projects)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "projects_project",
                "ordering": ["-updated_at"],
            },
        ),
    ]
