# Generated by Django 4.2.7 on 2025-10-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Human-readable name for the project, auto-generated from first message",
                max_length=255,
            ),
        ),
    ]
